export const RESET_STATE = 'RESET_STATE';
export const UPDATE_LOADING = 'UPDATE_LOADING';
export const UPDATE_SENDING = 'UPDATE_SENDING';
export const UPDATE_TOKEN_LIST = 'UPDATE_TOKEN_LIST';
export const UPDATE_TOKEN_BALANCE = 'UPDATE_TOKEN_BALANCE';
export const ADD_TOKEN = 'ADD_TOKEN';
