export const RESET_STATE = 'RESET_STATE';
export const UPDATE_LOADING = 'UPDATE_LOADING';
export const UPDATE_MINTING = 'UPDATE_MINTING';
export const CHANGE_MODE = 'CHANGE_MODE';
export const UPDATE_NFT_DATA = 'UPDATE_NFT_DATA';
export const UPDATE_NFT_METADATA = 'UPDATE_NFT_METADATA';
